"""project.godot scaffolding."""
from __future__ import annotations


def scaffold_project(name: str, main_scene: str = "res://main.tscn",
                     render_method: str = "mobile") -> str:
    return f"""; Engine generated by retrotool

config_version=5

[application]

config/name="{name}"
run/main_scene="{main_scene}"
config/features=PackedStringArray("4.3", "Forward Plus")

[rendering]

renderer/rendering_method="{render_method}"
textures/canvas_textures/default_texture_filter=0
"""
