"""Emit Python dataclasses from extracted ROM structures."""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class PyField:
    name: str
    type: str = "int"
    default: str | None = None
    comment: str = ""


@dataclass
class PyDataclass:
    name: str
    fields: list[PyField] = field(default_factory=list)
    comment: str = ""


def render_module(classes: list[PyDataclass], module_comment: str = "") -> str:
    out = ['"""{}"""'.format(module_comment or "Generated by retrotool.")]
    out.append("from __future__ import annotations")
    out.append("from dataclasses import dataclass, field")
    out.append("")
    for c in classes:
        if c.comment:
            out.append(f"# {c.comment}")
        out.append("@dataclass")
        out.append(f"class {c.name}:")
        if not c.fields:
            out.append("    pass")
        for f in c.fields:
            default = f" = {f.default}" if f.default else ""
            line = f"    {f.name}: {f.type}{default}"
            if f.comment:
                line += f"   # {f.comment}"
            out.append(line)
        out.append("")
    return '\n'.join(out)
